name: boardgame-project

on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: git clone code
      uses: actions/checkout@v4

    - name: installing unzip
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt install unzip -y 
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: uploading artifacts 
      uses: actions/upload-artifact@v4
      with:
        path: target/*.jar

    - name: trivy file scan
      run: trivy fs --format table -o trviy-fs-report.html . 

    - name: SonarQube scan code quality check
      uses:  sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
    
    - name: install JQ 
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt install jq 

    - name: sonarqube quality gate status 
      id: sonarqube-quality-gate-check
      timeout-minutes: 5
      uses: SonarSource/sonarqube-quality-gate-action@master
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}

    - name: setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: docker buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: build docker image
      run: |
        docker build -t sehindemitech/boardgames:latest . 

    - name: image scan 
      run: trivy image --format table -o trivy-image-report.html